spring.application.name=MiAplicacion

# Configuración de la base de datos H2
#spring.datasource.url=jdbc:h2:file:./concesionario_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Habilitar consola H2 para desarrollo
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.jpa.hibernate.ddl-auto=none

spring.jackson.deserialization.fail-on-unknown-properties=true

logging.level.net.sf.jasperreports=DEBUG